pool: Default

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack-connection'
- task: BrowserStackAppUploader@0
  inputs:
    appPath: 'WikipediaSample.apk'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
    options: '-P first'
