pool: Default

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'browserstack-connection'
- task: BrowserStackAppUploader@0
  inputs:
    appPath: 'WikipediaSample.apk'
- script: |
    mvn test -P first
  displayName: 'Run tests'
